### ISSUE TITLE
Validate jquery-grid Compatibility with jQuery v3

### ISSUE THREAD

**Issue by chrisllontop** [regolith-code/Aloha-Editor#1]
**Objective:**
The main aim of this task is to verify whether our current jquery-grid library is compatible with jQuery v3, as we are planning to upgrade jQuery from v1 to v3 in the "Aloha Editor" project.

**Details:**
We are in the process of updating the jQuery version of our "Aloha Editor" to enhance its features, fix bugs and improve its performance. However, before we can proceed with the upgrade, we need to ensure that all our dependent libraries and plugins, including jquery-grid, are compatible with the new jQuery version.

**Steps:**

1. Review the documentation of jquery-grid to look for any information about its compatibility with jQuery v3.
2. Check online forums, threads or any developer comments that may indicate jquery-grid's compatibility with jQuery v3.
3. Setup a testing environment where you can run a simple application using jquery-grid with jQuery v3. This will be a direct way to confirm compatibility. Make sure to test all the functionalities of jquery-grid that we are using in our project.
4. In case of incompatibilities found, document the specific issues and their impact on our project.
5. Research possible workarounds or alternatives if jquery-grid is found to be incompatible with jQuery v3.

**Expected Outcome:**

- A detailed report on whether jquery-grid is compatible with jQuery v3.
- If incompatible, list specific issues identified and their impact on our project.
- Suggest potential alternatives or fixes if any incompatibility issues arise.

**Comment by Jeremy15a** [comment]
The version of jqGrid currently used by the Aloha project only supports version 1.7 of jQuery. However, jqGrid continues to receive updates (it is currently at version 5.8.4). These versions are still being maintained and are compatible with the latest versions of jQuery (3.x.x) and jQuery UI.
