### ISSUE TITLE
Cypress Testing for Sourceview plugin

### ISSUE THREAD

**Issue by chrisllontop** [regolith-code/Aloha-Editor#37]
## Testing scenarios

- [x] Testing on sidebar
- [x] Testing on recognition of editable elements

 Testing the response on click of an editable:
- [x]   _It should show the html on the sidebar

- [x] Testing on "Widen" checkbox
- [x] Testing on "Show all source" checkbox

**Comment by JwanCortez93** [comment]
@christianllv 

For some reason, the cy.visit() doesn't work on this one so I can't even start to test it. I can't seem to figure out why.
