### ISSUE TITLE
Validate jstree Compatibility with jQuery v3

### ISSUE THREAD

**Issue by chrisllontop** [regolith-code/Aloha-Editor#6]
## Objective
The primary goal of this task is to assess the compatibility of our current jstree plugin with jQuery v3, as we are considering upgrading jQuery from v1 to v3 in our "Aloha Editor" project.

## Details
We are in the process of upgrading the jQuery version in our "Aloha Editor" to expand its functionalities, rectify bugs and enhance its performance. But before initiating the upgrade, we need to ensure that all our dependent libraries and plugins, including jstree, are fully compatible with the new jQuery version.

## Steps

1. Review the documentation of jstree to find any information about its compatibility with jQuery v3.
2. Look at online forums, threads, or developer comments that might indicate jstree's compatibility with jQuery v3.
3. Establish a testing environment where you can run a basic application using jstree with jQuery v3. This will be a direct way to confirm compatibility. Be sure to test all the functionalities of jstree that we are employing in our project.
4. In case of discovering any incompatibilities, document the specific issues and their potential impact on our project.
5. Investigate possible workarounds or alternatives if jstree is found to be incompatible with jQuery v3.

## Expected Outcome

- A comprehensive report detailing whether jstree is compatible with jQuery v3.
- If incompatible, provide a list of specific issues identified and their potential impact on our project.
- Suggest potential alternatives or remedies if any incompatibility issues are detected.

**Comment by JwanCortez93** [comment]
Js Tree is currently at its version 3.3.15, which, according to the changelog, is compatible with jQuery 3.5 since april 20, 2020. For reference, this is the 3.3.10 update of Js Tree project
